In [14]:
from rdkit import Chem
import pandas as pd
from ml_enhance import QuantumFPFileLoader
import numpy as np
from ml_enhance import parallelize

In [15]:
loader = QuantumFPFileLoader("../data/QFP_rerun/output")
files = loader.list_output_files()

In [16]:
wanted_properties = ["original_smiles", "output_smiles", "energy", "molecular_dipole_norm", "molecular_polarizability_mean", "homo_lumo_gap", "zero_point_energy", "atomization_energy", "xyz"]

In [18]:
def get_min_series(file):
    for df in loader.stream_conformer_dataframe(file, include_coords=True):
        min_series = df.loc[df["energy"].argmin(), wanted_properties]
        return min_series

In [35]:
# sample 1000 random molecules
rng = np.random.default_rng(65)
samples = rng.choice(files, size=2000, replace=False)

In [36]:
min_seriess = parallelize(get_min_series, samples)

min_df = pd.DataFrame(min_seriess).reset_index()

100%|██████████| 2000/2000 [05:23<00:00,  6.19it/s]

In [56]:
min_df["check"] = min_df["original_smiles"] == min_df["output_smiles"]
min_df = min_df[min_df["check"] == True][:1000].drop("check", axis=1)
min_df

,index,original_smiles,output_smiles,energy,molecular_dipole_norm,molecular_polarizability_mean,homo_lumo_gap,zero_point_energy,atomization_energy,xyz
3,1,[C:1]([C:2]([C:3]([H:12])([H:13])[H:14])([C:4]...,[C:1]([C:2]([C:3]([H:12])([H:13])[H:14])([C:4]...,-23.955609,0.718299,-36.701550,0.187059,90.435975,3.493217,"[[1, -2.536959020724405, -0.721172159005142, 0..."
4,5,[C:1]([C:2](=[O:3])[O:4][C:5]([C:6]([O:7][C:8]...,[C:1]([C:2](=[O:3])[O:4][C:5]([C:6]([O:7][C:8]...,-34.239757,0.640463,-48.783907,0.187788,98.052539,4.443413,"[[1, -2.2381618022040795, -1.4183267125004426,..."
5,0,[N:1]([c:2]1[n:3][c:4]([N:5]([H:20])[H:21])[n:...,[N:1]([c:2]1[n:3][c:4]([N:5]([H:20])[H:21])[n:...,-49.703118,0.448171,-115.241268,0.113663,116.287318,6.671730,"[[1, -4.5160743308785545, -1.703661518736344, ..."
6,0,[O:1]([c:2]1[c:3]([H:10])[c:4]([H:11])[c:5]([F...,[O:1]([c:2]1[c:3]([H:10])[c:4]([H:11])[c:5]([F...,-24.183334,1.083225,-46.366329,0.150865,58.490034,3.049158,"[[1, 2.784095106056287, -0.05331247717705534, ..."
7,0,[C:1]([C:2]([c:3]1[c:4]([H:18])[c:5]([C:6]([C:...,[C:1]([C:2]([c:3]1[c:4]([H:18])[c:5]([C:6]([C:...,-34.885173,0.035228,-87.876307,0.172679,166.125623,6.237452,"[[1, -1.9460524390143343, -2.986459015467147, ..."
...,...,...,...,...,...,...,...,...,...,...
1293,0,[Cl:1][c:2]1[c:3]([H:12])[c:4]([H:13])[c:5]2[c...,[Cl:1][c:2]1[c:3]([H:12])[c:4]([H:13])[c:5]2[c...,-31.759787,0.668316,-105.169883,0.142626,75.535343,4.167630,"[[1, 3.3964499317295753, -0.5475202930175784, ..."
1295,0,[C:1]([C:2]([O:3][C:4](=[O:5])[c:6]1[c:7]([H:2...,[C:1]([C:2]([O:3][C:4](=[O:5])[c:6]1[c:7]([H:2...,-43.810881,0.312693,-91.900501,0.119477,126.630209,6.044496,"[[1, 4.603841318317391, 0.13126006320673062, 0..."
1298,0,[O:1]([C:2](=[O:3])[c:4]1[n:5][c:6]([Cl:7])[c:...,[O:1]([C:2](=[O:3])[c:4]1[n:5][c:6]([Cl:7])[c:...,-34.536179,0.549746,-126.114629,0.095120,50.187447,3.465942,"[[1, 0.6934372186422421, 2.713385533498198, 0...."
1299,0,[N:1]([c:2]1[n:3][c:4]([N:5]([H:12])[H:13])[n:...,[N:1]([c:2]1[n:3][c:4]([N:5]([H:12])[H:13])[n:...,-27.672612,1.937623,-81.798610,0.133434,52.998894,3.175927,"[[1, 1.7342898663956012, 2.2912908793665583, -..."
1300,0,[C:1]([C:2]([C:3]([C:4]([C:5]([C:6]([C:7]([O:8...,[C:1]([C:2]([C:3]([C:4]([C:5]([C:6]([C:7]([O:8...,-27.215987,0.808361,-46.908602,0.437890,137.503704,4.563996,"[[1, 4.49188799983728, 0.28210881524862363, 0...."

In [57]:
# min_df.to_json("qm9_mols_no_prot.json", index=False)
min_df.to_json("aqsol_mols.json", index=False)

In [59]:
# df = pd.read_json("qm9_mols.json")
# df = pd.read_json("aqsol_mols.json")
df

,index,original_smiles,output_smiles,energy,molecular_dipole_norm,molecular_polarizability_mean,homo_lumo_gap,zero_point_energy,atomization_energy,xyz
3,1,[C:1]([C:2]([C:3]([H:12])([H:13])[H:14])([C:4]...,[C:1]([C:2]([C:3]([H:12])([H:13])[H:14])([C:4]...,-23.955609,0.718299,-36.701550,0.187059,90.435975,3.493217,"[[1, -2.5369590207, -0.7211721590000001, 0.314..."
4,5,[C:1]([C:2](=[O:3])[O:4][C:5]([C:6]([O:7][C:8]...,[C:1]([C:2](=[O:3])[O:4][C:5]([C:6]([O:7][C:8]...,-34.239757,0.640463,-48.783907,0.187788,98.052539,4.443413,"[[1, -2.2381618022, -1.4183267125, 0.588405348..."
5,0,[N:1]([c:2]1[n:3][c:4]([N:5]([H:20])[H:21])[n:...,[N:1]([c:2]1[n:3][c:4]([N:5]([H:20])[H:21])[n:...,-49.703118,0.448171,-115.241268,0.113663,116.287318,6.671730,"[[1, -4.5160743309, -1.7036615187000002, 0.026..."
6,0,[O:1]([c:2]1[c:3]([H:10])[c:4]([H:11])[c:5]([F...,[O:1]([c:2]1[c:3]([H:10])[c:4]([H:11])[c:5]([F...,-24.183334,1.083225,-46.366329,0.150865,58.490034,3.049158,"[[1, 2.7840951061, -0.0533124772, -4.8363e-06]..."
7,0,[C:1]([C:2]([c:3]1[c:4]([H:18])[c:5]([C:6]([C:...,[C:1]([C:2]([c:3]1[c:4]([H:18])[c:5]([C:6]([C:...,-34.885173,0.035228,-87.876307,0.172679,166.125623,6.237452,"[[1, -1.946052439, -2.9864590155, -0.744819860..."
...,...,...,...,...,...,...,...,...,...,...
1293,0,[Cl:1][c:2]1[c:3]([H:12])[c:4]([H:13])[c:5]2[c...,[Cl:1][c:2]1[c:3]([H:12])[c:4]([H:13])[c:5]2[c...,-31.759787,0.668316,-105.169883,0.142626,75.535343,4.167630,"[[1, 3.3964499317, -0.547520293, 0.00074802890..."
1295,0,[C:1]([C:2]([O:3][C:4](=[O:5])[c:6]1[c:7]([H:2...,[C:1]([C:2]([O:3][C:4](=[O:5])[c:6]1[c:7]([H:2...,-43.810881,0.312693,-91.900501,0.119477,126.630209,6.044496,"[[1, 4.6038413183, 0.1312600632, 0.9849656039]..."
1298,0,[O:1]([C:2](=[O:3])[c:4]1[n:5][c:6]([Cl:7])[c:...,[O:1]([C:2](=[O:3])[c:4]1[n:5][c:6]([Cl:7])[c:...,-34.536179,0.549746,-126.114629,0.095120,50.187447,3.465942,"[[1, 0.6934372186000001, 2.7133855335, 0.08631..."
1299,0,[N:1]([c:2]1[n:3][c:4]([N:5]([H:12])[H:13])[n:...,[N:1]([c:2]1[n:3][c:4]([N:5]([H:12])[H:13])[n:...,-27.672612,1.937623,-81.798610,0.133434,52.998894,3.175927,"[[1, 1.7342898664000002, 2.2912908794, -0.0007..."
1300,0,[C:1]([C:2]([C:3]([C:4]([C:5]([C:6]([C:7]([O:8...,[C:1]([C:2]([C:3]([C:4]([C:5]([C:6]([C:7]([O:8...,-27.215987,0.808361,-46.908602,0.437890,137.503704,4.563996,"[[1, 4.4918879998, 0.28210881520000003, 0.0061..."

In [ ]:
min_df["check"] = min_df["original_smiles"] == min_df["output_smiles"]
min_df["check"].sum()

In [ ]:
def test(molecule) -> None:
    smiles = molecule.output_smiles
    mol = Chem.MolFromSmiles(smiles, sanitize=False)

    charge = Chem.GetFormalCharge(mol)

    atom_symbol_map = {atom.GetAtomMapNum(): atom.GetSymbol() for atom in mol.GetAtoms()}
    geometry = molecule.xyz

    print(smiles)
    print(atom_symbol_map)

    print(list(sorted(map(lambda lst: lst[0], geometry))))

    atoms = []
    for atom_idx, x, y, z in geometry:
        sym = atom_symbol_map[int(atom_idx)]
        atoms.append(f"{sym} {x:.8f} {y:.8f} {z:.8f}")

    print("------------------------------------")

In [ ]:
for row in df.itertuples():
    if row.original_smiles != row.output_smiles:
        print(row.original_smiles)
        print(row.output_smiles)
        print("\n")