In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/QM9/data.csv")

In [93]:
rng = np.random.default_rng(10)
nums = rng.choice(df.index, 1013, replace=False)
nums

array([ 87942,  70440, 121936, ..., 121886,  39486, 106007], shape=(1013,))

In [94]:
sub_df = df.loc[nums, ["smiles", "mu", "alpha", "gap", "zpve", "U0_atom"]]

In [95]:
sub_df

,smiles,mu,alpha,gap,zpve,U0_atom
87942,[H]O[C@@]1(C([H])([H])[H])C2(O[C@]1([H])C([H])...,2.3929,79.029999,7.948446,4.882349,-85.460770
70440,[H]O[C@@]12C([H])([H])[N@H+]3C([H])([H])[C@]1(...,1.8703,75.150002,6.114398,4.104865,-77.043495
121936,[H]C1=C([H])C(C([H])([H])C#CC([H])([H])[H])=NO1,3.1128,78.360001,6.628694,3.361558,-71.956764
20499,[H]OC1=C([H])N([H])N=C1C([H])([H])C([H])([H])[H],0.5121,66.709999,6.413723,3.573453,-67.314606
125881,[H]C(=O)C1=C([H])ON=C1N([H])C([H])([H])[H],2.7754,71.180000,4.892607,3.058206,-65.635040
...,...,...,...,...,...,...
24359,[H][N-]C1N([H])C2=C(OC([H])=C2[H])C1([H])[H],2.8097,73.699997,5.330710,3.140384,-68.540459
115413,[H]O[C@]([H])(C([H])([H])[H])[C@]([H])(C#N)OC(...,3.9849,76.889999,8.302194,4.551431,-81.476173
121886,[H]C1=C(C#CC([H])([H])[H])C(C([H])([H])[H])=NO1,3.4385,83.419998,5.812352,3.345395,-72.341209
39486,[H]C1([H])[NH+]([C@]2([H])[C@]3([H])C45([H])OC...,1.8299,75.019997,8.280425,4.024509,-74.238220
106007,[H]C([H])([H])O[C@@]12C([H])([H])[N@H+]3C([H])...,1.2978,79.190002,8.032801,4.632603,-81.136879

In [96]:
df.loc[0, "pos"]

'tensor([[-1.2700e-02,  1.0858e+00,  8.0000e-03],\r\n        [ 2.2000e-03, -6.0000e-03,  2.0000e-03],\r\n        [ 1.0117e+00,  1.4638e+00,  3.0000e-04],\r\n        [-5.4080e-01,  1.4475e+00, -8.7660e-01],\r\n        [-5.2380e-01,  1.4379e+00,  9.0640e-01]])'

In [97]:
smiles_list = sub_df.smiles

In [98]:
from ml_enhance import get_preprocessed_smiles

def molecule_repr(id: str, smiles: str) -> dict:
    return {"id": id, "smiles": smiles}


def generate_json(inputs: list[dict]) -> dict:
    input_file = {
        "options": {
            "max_conformers": 32,
            "max_microstates": 8,
            "metadynamics": False
        },
        "runtime_options": {
        "num_vcpus": 1,
        "batch_size": 5
    },
    }

    input_file.update({"inputs": inputs})

    return input_file

# preprocess the smiles for the quantumFP program
preprocessed_smiles = [get_preprocessed_smiles(smiles) for smiles in smiles_list]

# Filter out all None instances returned from preprocess_smiles
cleaned_smiles = list(filter(lambda x: x not in (None, 'salt', 'atom'), preprocessed_smiles))

inputs = [molecule_repr(idx, smiles) for idx, smiles in enumerate(cleaned_smiles)]

json_obj = generate_json(inputs)

[13:24:21] Explicit valence for atom # 3 C, 5, is greater than permitted
[13:24:21] Explicit valence for atom # 2 C, 5, is greater than permitted
[13:24:21] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:24:21] Explicit valence for atom # 3 C, 5, is greater than permitted
[13:24:21] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:24:22] Explicit valence for atom # 2 C, 5, is greater than permitted
[13:24:22] Explicit valence for atom # 2 C, 5, is greater than permitted
[13:24:22] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:24:22] Explicit valence for atom # 6 C, 5, is greater than permitted
[13:24:22] Explicit valence for atom # 5 C, 5, is greater than permitted
[13:24:22] Explicit valence for atom # 4 C, 5, is greater than permitted
[13:24:22] Explicit valence for atom # 4 C, 5, is greater than permitted

In [99]:
sub_df

,smiles,mu,alpha,gap,zpve,U0_atom
87942,[H]O[C@@]1(C([H])([H])[H])C2(O[C@]1([H])C([H])...,2.3929,79.029999,7.948446,4.882349,-85.460770
70440,[H]O[C@@]12C([H])([H])[N@H+]3C([H])([H])[C@]1(...,1.8703,75.150002,6.114398,4.104865,-77.043495
121936,[H]C1=C([H])C(C([H])([H])C#CC([H])([H])[H])=NO1,3.1128,78.360001,6.628694,3.361558,-71.956764
20499,[H]OC1=C([H])N([H])N=C1C([H])([H])C([H])([H])[H],0.5121,66.709999,6.413723,3.573453,-67.314606
125881,[H]C(=O)C1=C([H])ON=C1N([H])C([H])([H])[H],2.7754,71.180000,4.892607,3.058206,-65.635040
...,...,...,...,...,...,...
24359,[H][N-]C1N([H])C2=C(OC([H])=C2[H])C1([H])[H],2.8097,73.699997,5.330710,3.140384,-68.540459
115413,[H]O[C@]([H])(C([H])([H])[H])[C@]([H])(C#N)OC(...,3.9849,76.889999,8.302194,4.551431,-81.476173
121886,[H]C1=C(C#CC([H])([H])[H])C(C([H])([H])[H])=NO1,3.4385,83.419998,5.812352,3.345395,-72.341209
39486,[H]C1([H])[NH+]([C@]2([H])[C@]3([H])C45([H])OC...,1.8299,75.019997,8.280425,4.024509,-74.238220
106007,[H]C([H])([H])O[C@@]12C([H])([H])[N@H+]3C([H])...,1.2978,79.190002,8.032801,4.632603,-81.136879

In [100]:
sub_df["cleaned_smiles"] = [pd.NA if smiles in (None, "salt", "atom") else smiles for smiles in preprocessed_smiles]

In [108]:
sub_df = sub_df.dropna()

In [109]:
sub_df.info()

<class 'pandas.DataFrame'>
Index: 1001 entries, 87942 to 106007
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   smiles          1001 non-null   str
 1   mu              1001 non-null   float64
 2   alpha           1001 non-null   float64
 3   gap             1001 non-null   float64
 4   zpve            1001 non-null   float64
 5   U0_atom         1001 non-null   float64
 6   cleaned_smiles  1001 non-null   str
dtypes: float64(5), str(2)
memory usage: 62.6 KB

In [110]:
sub_df.to_csv("qm9_values_of_mols.csv")

In [103]:
import json

with open("../data/QM9/qm9_test.json", "w") as f:
    json.dump(json_obj, f, indent=4)